server.port: 8081

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/codetrial
    username: postgres
    password: docker
logging:
  level:
    org.springframework.data.r2dbc: Debug
---
spring:
  profiles: test
  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password: mysecretpassword
---
spring:
  profiles: prod
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/codetrial
    username: docker
    password: codetrial
  logging:
    level:
      org.springframework.data.r2dbc: Debug